let modelsJson = [
  {
    id: 1,
    name: "COCA-COLA",
    img: "../img/coca.jpg",
    price: [6.0, 10.0, 17.0],
    sizes: ["1L", "2L", "2,5L"],
    description: "Refrigerante coca-cola 1L, 2L, 2,5L.",
  },
  {
    id: 2,
    name: "SUCO",
    img: "../img/suco.jpg",
    price: [6.0, 3.5, 5.0],
    sizes: ["Morango 500ML", "Maracujá 500ML", "Melancia 500ML"],
    description: "Sucos deliciosos com bastante gelo 500ML.",
  },
  {
    id: 3,
    name: "REFRIGERANTE LATA",
    img: "../img/refri.jpg",
    price: [6.5, 5.0, 5.5],
    sizes: ["Coca-cola 350ML", "Guaraná 350ML", "Fanta 350ML"],
    description: "Refrigerante coca-cola, guaraná, fanta Lata 350ML.",
  },
  {
    id: 4,
    name: "ÁGUA",
    img: "../img/agua.jpg",
    price: [2.5, 3.0, 6.0],
    sizes: ["Sem gás 500ML", "Com gás 500ML", "Sem gás 1L"],
    description: "Água mineral 500ML e 1L.",
  },
  {
    id: 5,
    name: "GUARANÁ",
    img: "../img/guarana.jpg",
    price: [7.0, 4.0, 3.5],
    sizes: ["Antarctica 2L", "Indaiá 2L", "Kuat 2L"],
    description: "Refrigerante guaraná antarctica, indaiá e kuat.",
  },
  {
    id: 6,
    name: "LIMONADA SUÍÇA",
    img: "../img/limonada.jpg",
    price: [3.5, 6.0, 7.5],
    sizes: ["250ML", "500ML", "700ML"],
    description: "Limonada com bastante gelo.",
  },
  {
    id: 7,
    name: "VINHO",
    img: "../img/vinho.webp",
    price: [30.0, 100.0, 25.0],
    sizes: ["Quinto do morgado", "Pérgola", "Campo largo"],
    description: "Vinhos suave 1L.",
  },
  {
    id: 8,
    name: "CAFÉ GELADO",
    img: "../img/cafe.jpg",
    price: [6.0, 10.0, 15.0],
    sizes: [
      "Cobertura de morango 300ML",
      "Cobertura de chocolate 500ML",
      "Cobertura de menta 700ML",
    ],
    description: "Café gelado com cobertura 300ML, 500ML, 700ML",
  },
];
